accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('my_page/<uuid:pk>/', views.MyPage, name='my_page'),
    path('name_edit/<uuid:pk>/', views.NameEdit, name='name_edit'),
    path('address_list/<uuid:pk>/', views.AddressList, name='address_list'),
    path('address_create/<uuid:pk>/', views.AddressCreate, name='address_create'),
    path('address_edit/<uuid:pk>/', views.AddressEdit, name='address_edit'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shop.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.Home, name='home'),
    path('list/', views.ProductsList, name='list'),
    path('products/', views.Products, name='products'),
    path('category_parent/', views.CategoryParent, name='category_parent'),
    path('category_child/', views.CategoryChild, name='category_child'),
    path('products_images', views.ProductsImages, name='products_images'),
    path('category/<uuid:pk>/', views.Category, name='category'),
    path('product_detail/<uuid:pk>/', views.ProductsDetail, name='product_detail'),
    path('search/', views.ProductsSearch, name='search'),
    path('edit/<uuid:pk>/', views.Edit, name='edit'),
    path('cart/', views.cart, name='cart'),
    path('cart_edit/<uuid:pk>/', views.CartEdit, name='cart_edit'),
    path('delete/<uuid:pk>/', views.Delete, name='delete'),
    path('contact/', views.Contact, name='contact'),
]

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.contrib.auth.validators import UnicodeUsernameValidator

from django.utils import timezone

from django.conf import settings

from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail

import uuid

class CustomUserAddress(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='ユーザーID')
    main = models.BooleanField(verbose_name="メイン住所", default=False)
    name = models.CharField(verbose_name='名前', max_length=30, blank=False, null=True)
    prefcode = models.CharField(verbose_name='郵便番号', max_length=8, blank=False, null=True)
    address1 = models.CharField(verbose_name='都道府県', max_length=40, blank=False, null=True)
    address2 = models.CharField(verbose_name='市区町村名', max_length=40, blank=False, null=True)
    address3 = models.CharField(verbose_name='町域名', max_length=40, blank=False, null=True)

    def __str__(self):
        return self.name

class CustomUser(AbstractBaseUser, PermissionsMixin):
    username_validator = UnicodeUsernameValidator()

    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    username = models.CharField(
                    _('username'),
                    max_length=150,
                    unique=True,
                    help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
                    validators=[username_validator],
                    error_messages={
                        'unique': _("A user with that username already exists."),
                    },
                )
    phone_number = models.CharField(verbose_name='電話番号', max_length=40, blank=True, null=True)
    email = models.EmailField(verbose_name='メールアドレス', unique=True,
                              error_messages={
                                  'unique': ("同一のメールアドレスが既に登録されています"),
                              }, )
    name = models.CharField(verbose_name='名前', blank=False, max_length=30)
    name_kana = models.CharField(verbose_name='名前(ふりがな)', blank=False, max_length=60)
    is_staff = models.BooleanField(
                    _('staff status'),
                    default=False,
                    help_text=_('Designates whether the user can log into this admin site.'),
                )
    is_active = models.BooleanField(
                    _('active'),
                    default=True,
                    help_text=_(
                        'Designates whether this user should be treated as active. '
                        'Unselect this instead of deleting accounts.'
                    ),
                )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'

    REQUIRED_FIELDS = ["name", "name_kana", "email"]

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        #abstract = True

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def addresses(self):
        return CustomUserAddress.objects.filter(user_id=self.id)

    def __str__(self):
        return self.username

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

from django import forms
from .models import CustomUser, CustomUserAddress

class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ['username', "email", 'name', 'name_kana']

class NameEditForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'name', 'name_kana']

class AddressForm(forms.ModelForm):
    class Meta:
        model = CustomUserAddress
        fields = ['user_id', 'name', 'prefcode', 'address1', 'address2', 'address3', 'main']

# ↑と↓で内容が重複しているので、編集時にも流用してもよいのでは？

class AddressEditForm(forms.ModelForm):
    class Meta:
        model = CustomUserAddress
        fields = ['user_id', 'name', 'prefcode', 'address1', 'address2', 'address3', 'main']





accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import View

from .models import CustomUser, CustomUserAddress
from .forms import SignupForm, NameEditForm, AddressForm, AddressEditForm

from shop.models import ProductCategoryParent, ProductCategoryChild, Product, Cart, Contacts

class AccountsMyPageView(View):
    def get(self, request, pk, *args, **kwargs):

        context = {}

        context['user'] = CustomUser.objects.filter(id=pk).first()
        context['categories'] = ProductCategoryParent.objects.all()
        context['category'] = ProductCategoryChild.objects.all()
        context["num"] = Cart.objects.filter(user=request.user.id).count()

        return render(request, 'accounts/accounts_page.html', context)

MyPage = AccountsMyPageView.as_view()

class NameEditView(View):
    def get(self, request, pk, *args, **kwargs):

        context = {}

        context['user'] = CustomUser.objects.filter(id=pk).first()
        context['categories'] = ProductCategoryParent.objects.all()
        context['category'] = ProductCategoryChild.objects.all()
        context["num"] = Cart.objects.filter(user=request.user.id).count()

        return render(request, "accounts/name_edit.html", context)

    def post(self, request, pk, *args, **kwargs):

        account = CustomUser.objects.filter(id=pk).first()

        form = NameEditForm(request.POST, instance=account)

        if form.is_valid():
            print("バリデーションOK")
            form.save()
        else:
            print("バリデーションNG")
            print(form.errors)

        return redirect("accounts:name_edit", pk)

NameEdit = NameEditView.as_view()

class AccountsAddressListView(View):
    def get(self, request, pk, *args, **kwargs):

        context = {}

        context['user'] = CustomUser.objects.filter(id=pk).first()
        context["num"] = Cart.objects.filter(user=request.user.id).count()

        return render(request, 'accounts/address_list.html', context)

AddressList = AccountsAddressListView.as_view()

class AddressCreateView(View):
    def get(self, request, pk, *args, **kwargs):

        context = {}

        context['user'] = CustomUser.objects.filter(id=pk).first()
        context["num"] = Cart.objects.filter(user=request.user.id).count()

        return render(request, 'accounts/address_create.html', context)

    def post(self, request, pk, *args, **kwargs):

        copied = request.POST.copy()
        copied["user_id"] = request.user.id

        form = AddressForm(copied)

        if form.is_valid():
            print("バリデーションOK")
            form.save()
        else:
            print("バリデーションNG")
            print(form.errors)

        return redirect('accounts:address_create', pk)

AddressCreate = AddressCreateView.as_view()


class AccountsAddressEditView(View):

    def get(self, request, pk, *args, **kwargs):

        context = {}

        context['user'] = CustomUser.objects.filter(id=pk).first()
        context["num"] = Cart.objects.filter(user=request.user.id).count()

        return render(request, 'accounts/address_edit.html', context)

    def post(self, request, pk, *args, **kwargs):

        #TODO:共通箇所
        #指定されたpkが存在するかチェック
        address = CustomUserAddress.objects.filter(id=pk, user_id=request.user.id).first()

        #存在しない場合
        #ここはアーリーリターンを使いましょう
        if not address:
            return redirect('accounts:address_edit', pk)



        #TODO:ここでmainの値のみ書き換える場合、バリデーション用のフォームクラスは不要。
        #TODO:以下、mainを変える場合のみの処理(実践ではPATCHメソッドに下記の処理を割り当て)
        """
        #全てのデータをFalseに
        addresses = CustomUserAddress.objects.filter(user_id=request.user.id, main=True)

        for a in addresses:
            a.main = False
            a.save()

        #指定された値をTrueに変換して保存。
        address.main = True
        address.save()
        """


        #TODO:もし全てのデータを同時に書き換える場合、バリデーション用のフォームクラスは必要

        copied              = request.POST.copy()
        copied["user_id"]   = request.user.id

        form = AddressEditForm(copied, instance=address)

        if not form.is_valid():
            print('バリデーションNG')
            print(form.errors)
            return redirect('accounts:address_edit', pk)


        #TODO:この時、mainの値がTrueであれば、既に記録されているデータのTrueをFalseにする。
        cleaned = form.clean()

        if cleaned["main"]:
            addresses = CustomUserAddress.objects.filter(user_id=request.user.id, main=True)

            for a in addresses:
                a.main = False
                a.save()

        #そして保存する。
        print('バリデーションOK')
        form.save()

        return redirect('accounts:address_edit', pk)

AddressEdit = AccountsAddressEditView.as_view()

templates/accounts/accounts_edit.html
{% extends "accounts/base.html" %}
{% load static %}
{% load param_change %}
{% block content %}

        <nav>
            <ul class="gnavi">
                <li><a href="/">ご注文履歴</a></li>
                <li><a href="/">お気に入り一覧</a></li>
                <li class="current"><a href="{% url 'accounts:my_page' user.id %}">会員情報編集</a></li>
                <li><a class="nav-link" href="{% url 'accounts:address_list' user.id %}">お届け先一覧</a></li>
                <li><a href="{% url 'shop:contact' %}">退会手続き</a></li>
            </ul>

<div class="text-center my-5">
    <div class="row">
        {% for user in users %}
        <div class="col-lg-3 col-md-6">
            <div class="card-body text-center px-2 py-3">
                <p class="mb-0 text-secondary">{{ user.prefcode }}</p>
                <h5 class="font-weight-bold">{{ user.address1 }}</h5>
                <h4 class="font-weight-bold">{{ user.address2 }}円</h4>
                <h4 class="font-weight-bold">{{ user.address3 }}円</h4>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<!--<div class="account_edit">-->
<!--    <form method="POST" action="{% url 'accounts:accounts_edit' user.id %}">-->
<!--        {% csrf_token %}-->
<!--        <div>ユーザー名:<input type="text" name="username" value="{{ user.username }}"></div>-->
<!--        <div>Eメールアドレス:{{ user.email }}</div>-->
<!--        <div>氏名:<input type="text" name="name" value="{{ user.name }}" disabled></div>-->
<!--        <div>ふりがな:<input type="text" name="name_kana" value="{{ user.name_kana }}" disabled></div>-->
<!--        <div><input type="submit" value="変更"></div>-->
<!--    </form>-->

<!--    <a href="{% url 'accounts:my_page' user.id %}">戻る</a>-->
<!--</div>-->

{% endblock %}

templates/accounts/accounts_page.html
{% extends "accounts/base.html" %}
{% load static %}
{% block content %}

        <nav>
            <ul class="gnavi">
                <li><a href="/">ご注文履歴</a></li>
                <li><a href="/">お気に入り一覧</a></li>
                <li class="current"><a href="{% url 'accounts:my_page' user.id %}">会員情報編集</a></li>
                <li><a href="{% url 'accounts:address_list' user.id %}">お届け先一覧</a></li>
                <li><a href="{% url 'shop:contact' %}">退会手続き</a></li>
            </ul>
        </nav>

        <div class="card card-profile my-5 mx-auto">
            <div class="card-body">
                <h5 class="card-title text-center">プロフィール</h5>
                <table class="profile_table mb-4">
                    <tbody>
                    <tr>
                        <th class="header">名前</th>
                        <td class="data">{{ user.name }}</td>
                        <td class="data"><a class="btn btn-lg btn-warning btn-block" href="{% url 'accounts:name_edit' user.id %}">編集</a></td>
                    </tr>
                    <tr>
                        <th class="header">メールアドレス</th>
                        <td class="data">{{ user.email }}</td>
                        <td class="data"><a class="btn btn-lg btn-warning btn-block" href="{% url 'account_email' %}">編集</a></td>
                    </tr>
                    {% for address in request.user.addresses %}
                    <tr>
                        <th class="header">住所</th>
                        <td class="data">〒{{ address.prefcode }}<br>{{ address.address1 }}{{ address.address2 }}{{ address.address3 }}</td>
                        <td class="data"><a class="btn btn-lg btn-warning btn-block" href="{% url 'accounts:address_list' address.id %}">編集</a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
<!--                <div class="button mx-auto">-->
<!--                    -->
<!--                </div>-->
            </div>
        </div>

{% endblock %}

templates/accounts/address_create.html
{% extends "accounts/base.html" %}
{% load static %}
{% block content %}

<div class="card card-profile my-5 mx-auto">
    <div class="card-body">
        <h5 class="card-title text-center"></h5>
        <form method="POST" action="{% url 'accounts:address_create' user.id %}">
            {% csrf_token %}
            <table class="profile_table mb-4">
                <tbody>
                <tr>
                    <th class="header">氏名</th>
                    <td class="data"><input type="text" name="name" placeholder="氏名"></td>
                </tr>
                <tr>
                    <th class="header">郵便番号</th>
                    <td class="data"><input id="postcode" type="text" name="prefcode" placeholder="ここに郵便番号を入力する(ハイフン不要)"></td>
                    <td class="data"><input id="postcode_search" type="button" value="郵便番号検索"></td>
                </tr>
                <tr>
                    <th class="header">都道府県</th>
                    <td class="data"><input id="prefecture" type="text" name="address1" placeholder="都道府県"></td>
                </tr>
                <tr>
                    <th class="header">市区町村名</th>
                    <td class="data"><input id="city" type="text" name="address2" placeholder="市区町村名"></td>
                </tr>
                <tr>
                    <th class="header">残りの住所</th>
                    <td class="data"><input id="address" type="text" name="address3" placeholder="残りの住所"></td>
                </tr>
                <tr>
                    <th class="header">既定の住所に設定</th>
                    <td class="data"><input type="checkbox" name="main"></td>
                </tr>
                </tbody>
            </table>
            <div class="button mx-auto">
                <input class="btn btn-lg btn-warning btn-block" type="submit" value="登録">
            </div>
        </form>
    </div>
</div>

{% endblock %}

templates/accounts/address_edit.html
{% extends "accounts/base.html" %}
{% load static %}
{% block content %}


<div class="card card-profile my-5 mx-auto">
    <div class="card-body">
        <h5 class="card-title text-center"></h5>
        <form method="POST">
            {% csrf_token %}
            <table class="profile_table mb-4">
                <tbody>
                <tr>
                    <th class="header">郵便番号</th>
                    <td class="data form_wrap form_wrap-2"><input type="text" name="name" placeholder="氏名"></td>
                </tr>
                <tr>
                    <th class="header">郵便番号</th>
                    <td class="data"><input id="postcode" type="text" name="prefcode" placeholder="ここに郵便番号を入力する(ハイフン不要)"></td>
                    <td class="data"><input id="postcode_search" type="button" value="郵便番号検索"></td>
                </tr>
                <tr>
                    <th class="header">都道府県</th>
                    <td class="data"><input id="prefecture" type="text" name="address1" placeholder="都道府県"></td>
                </tr>
                <tr>
                    <th class="header">住所</th>
                    <td class="data"><input id="city" type="text" name="address2" placeholder="市区町村名"></td>
                </tr>
                <tr>
                    <th class="header">住所</th>
                    <td class="data"><input id="address" type="text" name="address3" placeholder="残りの住所"></td>
                </tr>

                </tbody>
            </table>
            <div class="button mx-auto">
                <input class="btn btn-lg btn-warning btn-block" type="submit" value="登録">
            </div>
        </form>
<!--        <div class="button mx-auto">-->
<!--            <input class="btn btn-lg btn-warning btn-block" type="submit" value="登録">-->
<!--        </div>-->
    </div>
</div>
{% endblock %}

templates/accounts/address_list.html
{% extends "accounts/base.html" %}
{% load static %}
{% block content %}

        <nav>
            <ul class="gnavi">
                <li><a href="/">ご注文履歴</a></li>
                <li><a href="/">お気に入り一覧</a></li>
                <li class="current"><a href="{% url 'accounts:my_page' user.id %}">会員情報編集</a></li>
                <li><a class="nav-link" href="{% url 'accounts:address_list' user.id %}">お届け先一覧</a></li>
                <li><a href="{% url 'shop:contact' %}">退会手続き</a></li>
            </ul>
        </nav>

        <div class="card card-profile my-5 mx-auto">
            <div class="card-body">
                <h5 class="card-title text-center">プロフィール</h5>
                {% for address in request.user.addresses %}
                <table class="profile_table mb-4">
                    <tbody>
                    <tr>
                        <th class="header">名前</th>
                        <td class="data">{{ address.name }}</td>
                    </tr>
                    <tr>
                        <th class="header">住所</th>
                        <td class="data">〒{{ address.prefcode }}<br>{{ address.address1 }}{{ address.address2 }}{{ address.address3 }}
                        </td>
                    </tr>
                    </tbody>
                </table>
                <div class="button mx-auto">
                    <a class="btn btn-lg btn-warning btn-block" href="{% url 'accounts:address_edit' address.id %}">編集</a>
                    <td class="data"><a class="btn btn-lg btn-warning btn-block" href="{% url 'accounts:address_create' address.id %}">作成</a></td>
                </div>
                {% endfor %}
            </div>
        </div>

{% endblock %}

templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'shop/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>ECサイト</title>
    <script src="{% static 'shop/js/script.js' %}"></script>
    <script src="{% static 'common/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'common/js/slick.min.js' %}"></script>
</head>
<body>
<div class="wrapper">
    <div class="containers">

        <header class="header_">
            <div class="header__inner_">
                <div class="header_title_">
                    <a class="navbar-brand" href="{% url 'shop:home' %}">ECサイト</a>
                </div>
                <nav>
                    <ul class="gnavi">
                        <li><a href="{% url 'shop:home' %}">ホーム</a></li>
                        <li><a href="{% url 'shop:list' %}">Product</a></li>
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'accounts:my_page' user.id %}">アカウント</a></li>
                        {% else %}
                        <li><a href="{% url 'account_login' %}">ログイン</a></li>
                        {% endif %}
                        <li class="current"><a class="nav-link" href="{% url 'shop:cart' %}">カート<span class="badge badge-pill badge-warning">{{ request.num }}</span></a></li>

                        <li><a href="{% url 'shop:contact' %}">CONTACT</a></li>
                        <li>
                            <form role="search" action="{% url 'shop:search' %}" method="GET">
                                <input type="text" name="search" value="{{ request.GET.search }}" id="search-text">
                            </form>
                        </li>
                    </ul>
                </nav>
            </div>
        </header>

        <div class="container">{% block content %} {% endblock %}</div>
    </div> <!-- containers -->
    <footer class="py-2 bg-dark">
        <p class="m-0 text-center text-white">
            &copy; ECsite
        </p>
    </footer>
</div> <!-- wrapper -->
</body>
</html>

templates/accounts/name_edit.html
{% extends "accounts/base.html" %}
{% load static %}
{% load param_change %}

{% block content %}
        <nav>
            <ul class="gnavi">
                <li><a href="/">ご注文履歴</a></li>
                <li><a href="/">お気に入り一覧</a></li>
                <li class="current"><a href="{% url 'accounts:my_page' user.id %}">会員情報編集</a></li>
                <li><a class="nav-link" href="{% url 'shop:cart' %}">お届け先一覧</a></li>
                <li><a href="{% url 'shop:contact' %}">退会手続き</a></li>

            </ul>
        </nav>

        <form method="POST">
            {% csrf_token %}
            <ul>
                <li>ユーザー名: <input type="text" name="username" value="{{ user.username }}"></li>
                <li>新しい名前: <input type="text" name="name" value="{{ user.name }}"></li>
                <li>ふりがな: <input type="text" name="name_kana" value="{{ user.name_kana }}"></li>
                <li><input type="submit" value="変更を保存"></li>
            </ul>

        </form>

{% endblock %}