accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('my_page/<uuid:pk>/', views.MyPage, name='my_page'),
    path('name_edit/<uuid:pk>/', views.NameEdit, name='name_edit'),
    path('address_list/<uuid:pk>/', views.AddressList, name='address_list'),
    path('address_create/<uuid:pk>/', views.AddressCreate, name='address_create'),
    path('address_edit/<uuid:pk>/', views.AddressEdit, name='address_edit'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shop.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.Home, name='home'),
    path('list/', views.ProductsList, name='list'),
    path('products/', views.Products, name='products'),
    path('category_parent/', views.CategoryParent, name='category_parent'),
    path('category_child/', views.CategoryChild, name='category_child'),
    path('products_images', views.ProductsImages, name='products_images'),
    path('category/<uuid:pk>/', views.Category, name='category'),
    path('product_detail/<uuid:pk>/', views.ProductsDetail, name='product_detail'),
    path('search/', views.ProductsSearch, name='search'),
    path('edit/<uuid:pk>/', views.Edit, name='edit'),
    path('cart/', views.cart, name='cart'),
    path('cart_edit/<uuid:pk>/', views.CartEdit, name='cart_edit'),
    path('delete/<uuid:pk>/', views.Delete, name='delete'),
    path('contact/', views.Contact, name='contact'),
]

shop/forms.py
from django import forms

from .models import ProductCategoryParent, ProductCategoryChild, Product, ProductImage, Cart, Contacts

class ProductCategoryParentForm(forms.ModelForm):
    class Meta:
        model = ProductCategoryParent
        fields = ['name']

class ProductCategoryChildForm(forms.ModelForm):
    class Meta:
        model = ProductCategoryChild
        fields = ['category', 'name']

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['category', 'name', 'stock', 'image', 'description', 'price', 'situation']

class ProductsImageForm(forms.ModelForm):
    class Meta:
        model = ProductImage
        fields = ['image', 'product']

class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['category', 'name', 'stock', 'image', 'description', 'price', 'situation']

class CartForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = ['user', 'product', 'amount']

class CartEditForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = ['amount']

class ContactsForm(forms.ModelForm):
    class Meta:
        model = Contacts
        fields = ['user_id', 'name', 'email', 'title', 'contents']

shop/views.py
from django.shortcuts import render, redirect
from django.views.generic import View

from django.contrib import messages

from django.db.models import Q
from django.core.paginator import Paginator

from accounts.models import CustomUser
# from accounts.forms import SignupForm, AccountEditForm

from .models import ProductCategoryParent, ProductCategoryChild, Product, ProductImage, Cart, Contacts
from .forms import ProductCategoryParentForm, ProductCategoryChildForm, ProductForm, ProductsImageForm, ProductEditForm, CartForm, ContactsForm

class HomeView(View):
    def get(self, request, *args, **kwargs):

        context = {}

        context["products"] = Product.objects.all()[:4]
        context['categories'] = ProductCategoryParent.objects.all()
        context['category'] = ProductCategoryChild.objects.all()
        context['users'] = CustomUser.objects.all()
        context["num"] = Cart.objects.filter(user=request.user.id).count()

        return render(request, 'shop/home.html', context)

Home = HomeView.as_view()

class ProductsListView(View):
    def get(self, request, *args, **kwargs):

        context = {}

        context["products"] = Product.objects.all()
        context['category'] = ProductCategoryParent.objects.all()
        context['categories'] = ProductCategoryChild.objects.all()
        context['users'] = CustomUser.objects.all()
        context["num"] = Cart.objects.filter(user=request.user.id).count()

        sort_list = [
            {"key": "price", "value": "値段が安い順"},
            {"key": "-price", "value": "値段が高い順"},
            {'key': 'dt', 'value': '最新順'},
        ]

        keys = [s["key"] for s in sort_list]

        context["sort_list"] = sort_list


        if "order_by" in request.GET:

            #その並び替えが指定のリストの中にある。

            if request.GET["order_by"] in keys:

                context["products"] = Product.objects.order_by(request.GET["order_by"])
            else:
                context["products"] = Product.objects.all()
        else:
            context["products"] = Product.objects.all()

        return render(request, 'shop/product_list.html', context)

ProductsList = ProductsListView.as_view()

class ProductsSearchView(View):
    def get(self, request, *args, **kwargs):

        if "search" in request.GET:

            if request.GET["search"] == "" or request.GET["search"].isspace():
                return redirect("shop:search")

            search = request.GET["search"].replace("　", " ")
            search_list = search.split(" ")

            query = Q()
            for word in search_list:
                query &= Q(name__contains=word)

            # .order_byメソッドで並び替えしないと、paginatorでWARNINGが出る。
            data = Product.objects.filter(query).order_by("id")
        else:
            data = Product.objects.all().order_by("id")

        # ===========ここからページネーション処理================
        paginator = Paginator(data, 4)

        if "page" in request.GET:
            data = paginator.get_page(request.GET["page"])
        else:
            data = paginator.get_page(1)

        context = {"data": data}
        context['category'] = ProductCategoryParent.objects.all()
        context['users'] = CustomUser.objects.all()
        context["num"] = Cart.objects.filter(user=request.user.id).count()

        return render(request, "shop/search.html", context)

    def post(self, request, *args, **kwargs):

        return redirect("shop:search")

ProductsSearch = ProductsSearchView.as_view()

class ProductsView(View):
    def get(self, request, *args, **kwargs):

        context = {}

        context['products'] = Product.objects.all()
        context['category'] = ProductCategoryParent.objects.all()
        context['categories'] = ProductCategoryChild.objects.all()

        return render(request, 'shop/products_create.html', context)

    def post(self, request, *args, **kwargs):

        form = ProductForm(request.POST, request.FILES)

        if form.is_valid():
            print('バリデーションOK')
            messages.info(request, "バリデーションOK")
            form.save()
        else:
            print('バリデーションNG')
            print(form.errors)
            messages.add_message(request, messages.INFO, form.errors)

        return redirect('shop:products')

Products = ProductsView.as_view()

class ProductCategoryParentView(View):
    def post(self, request, *args, **kwargs):

        form = ProductCategoryParentForm(request.POST)

        if form.is_valid():
            print('バリデーションOK')
            messages.info(request, "バリデーションOK")
            form.save()
        else:
            print('バリデーションNG')
            print(form.errors)
            messages.add_message(request, messages.INFO, form.errors)

        return redirect('shop:products')

CategoryParent = ProductCategoryParentView.as_view()

class ProductCategoryChildView(View):
    def post(self, request, *args, **kwargs):

        form = ProductCategoryChildForm(request.POST)

        if form.is_valid():
            print('バリデーションOK')
            messages.info(request, "バリデーションOK")
            form.save()
        else:
            print('バリデーションNG')
            print(form.errors)
            messages.add_message(request, messages.INFO, form.errors)

        return redirect('shop:products')

CategoryChild = ProductCategoryChildView.as_view()

class ProductImagesView(View):
    def post(self, request, *args, **kwargs):

        print(request.POST)
        print(request.FILES)

        form = ProductsImageForm(request.POST, request.FILES)

        if form.is_valid():

            print('バリデーションOK')
            messages.info(request, "バリデーションOK")

            form.save()

        else:

            print('バリデーションNG')
            print(form.errors)
            messages.add_message(request, messages.INFO, form.errors)

        data = {"error": True}

        from django.http import JsonResponse

        return JsonResponse(data)

ProductsImages = ProductImagesView.as_view()

class CategoryView(View):
    def get(self, request, pk, *args, **kwargs):

        context = {}

        # context['category'] = ProductCategory.objects.filter(id=pk).first()
        # context['category'] = ProductCategory.objects.all()
        context['category'] = ProductCategoryChild.objects.filter(id=pk).first()
        context['category'] = ProductCategoryChild.objects.all()
        context['categories'] = ProductCategoryParent.objects.filter(id=pk).first()
        context['categories'] = ProductCategoryParent.objects.all()
        context['products'] = Product.objects.filter(category_id=pk)
        context["num"] = Cart.objects.filter(user=request.user.id).count()

        sort_list = [
            {"key": "price", "value": "値段が安い順"},
            {"key": "-price", "value": "値段が高い順"},
            {'key': 'dt', 'value': '最新順'},
        ]

        keys = [s["key"] for s in sort_list]


        context["sort_list"] = sort_list

        #並び替えが指定されている。

        if "order_by" in request.GET:

            #その並び替えが指定のリストの中にある。

            if request.GET["order_by"] in keys:

                context["products"] = Product.objects.filter(category_id=pk).order_by(request.GET["order_by"])
            else:
                context['products'] = Product.objects.filter(category_id=pk)
        else:
            context['products'] = Product.objects.filter(category_id=pk)

        return render(request, 'shop/home.html', context)

Category = CategoryView.as_view()

class ProductDetailView(View):
    def get(self, request, pk, *args, **kwargs):

        context = {}

        context['products'] = Product.objects.filter(id=pk).first()
        # context['images'] = ProductImage.objects.filter(product_id=pk)
        context["num"] = Cart.objects.filter(user=request.user.id).count()

        return render(request, 'shop/product_detail.html', context)

    def post(self, request, pk, *args, **kwargs):

        # ここでユーザーのカートへ追加
        if request.user.is_authenticated:
            # TIPS:ここで既に同じ商品がカートに入っている場合、レコード新規作成ではなく、既存レコードにamount分だけ追加する。
            copied = request.POST.copy()

            copied["user"] = request.user.id
            copied["product"] = pk

            form = CartForm(copied)

            if not form.is_valid():
                print("バリデーションNG")
                return redirect("shop:product_detail", pk)

            # print("バリデーションOK")

            # TIPS:ここで既に同じ商品がカートに入っている場合、レコード新規作成ではなく、既存レコードにamount分だけ追加する。
            cart = Cart.objects.filter(user=request.user.id, product=pk).first()

            if cart:
                cleaned = form.clean()

                # TODO:ここでカートに数量を追加する時、追加される数量が在庫数を上回っていないかチェックする。上回る場合は拒否する。
                stock = Product.objects.filter(id=pk).first().stock

                if stock >= cart.amount + cleaned["amount"]:
                    # カート内商品は在庫数以下につき、保存OK
                    cart.amount += cleaned["amount"]
                    cart.save()

                else:
                    print("在庫数を超過しているため、カートに追加できません。")

            else:
                # 存在しない場合は新規作成
                form.save()

        else:
            print("未認証です")
            return redirect('account_login')
            # TODO:未認証ユーザーにはCookieにカートのデータを格納するのも良い

        return redirect("shop:product_detail", pk)

ProductsDetail = ProductDetailView.as_view()

class ProductEditView(View):
    def get(self, request, pk, *args, **kwargs):

        context = {}

        context['products'] = Product.objects.filter(id=pk).first()
        context['category'] = ProductCategoryChild.objects.all()


        return render(request, 'shop/edit.html', context)

    def post(self, request, pk, *args, **kwargs):


templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'shop/css/style.css' %}">

    <title>ECサイト</title>
    <script src="{% static 'shop/js/script.js' %}"></script>
    <script src="{% static 'common/js/jquery-3.6.0.min.js' %}"></script>
</head>
<body>
<div class="wrapper">
    <div class="containers">

        <header class="header_">
            <div class="header__inner_">
                <div class="header_title_">
                    <a class="navbar-brand" href="{% url 'shop:home' %}">ECサイト</a>
                    <form role="search" action="{% url 'shop:search' %}" method="GET">
                        <input type="text" name="search" value="{{ request.GET.search }}" id="search-text">
                    </form>
                </div>
                <nav>
                    <ul class="gnavi">
                        <li class="current"><a href="{% url 'shop:home' %}">ホーム</a></li>
                        <li class="has-child"><a href="{% url 'shop:list' %}">Product</a>
                            <ul>
                                {% for category in categories %}
                                <li><a href="{% url 'shop:category' category.id %}">{{ category.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'accounts:my_page' user.id %}">アカウント</a></li>
                        {% else %}
                        <li><a href="{% url 'account_login' %}">ログイン</a></li>
                        {% endif %}
                        <li><a class="nav-link" href="{% url 'shop:cart' %}">カート<span class="badge badge-pill badge-warning">{{ request.num }}</span></a></li>
                        <li><a href="{% url 'shop:contact' %}">CONTACT</a></li>
<!--                        <li>-->
<!--                            <form role="search" action="{% url 'shop:search' %}" method="GET">-->
<!--                                <input type="text" name="search" value="{{ request.GET.search }}" id="search-text">-->
<!--                            </form>-->
<!--                        </li>-->
                    </ul>
                </nav>
            </div>
        </header>

        <!--<nav class="navbar navbar-expand-lg navbar-dark bg-dark">-->
        <!--    <div class="container">-->
        <!--        <a class="navbar-brand" href="/">ECサイト</a>-->
        <!--        <ul class="navbar-nav ml-auto">-->
        <!--            <li class="nav-item">-->
        <!--                <a class="nav-link" href="{% url 'shop:home' %}">ホーム</a>-->
        <!--            </li>-->
        <!--            {% if user.is_authenticated %}-->
        <!--            <li class="nav-item">-->
        <!--                <a class="nav-link" href="{% url 'accounts:my_page' user.id %}">プロフィール</a>-->
        <!--            </li>-->
        <!--            <li class="nav-item">-->
        <!--                <a class="nav-link" href="{% url 'account_logout' %}">ログアウト</a>-->
        <!--            </li>-->
        <!--            <li class="nav-item">-->
        <!--                <a class="nav-link" href="{% url 'shop:cart' %}">カート<span class="badge badge-pill badge-warning">{{ num }}</span></a>-->
        <!--            </li>-->
        <!--            {% else %}-->
        <!--&lt;!&ndash;            <li class="nav-item">&ndash;&gt;-->
        <!--&lt;!&ndash;                <a class="nav-link" href="{% url 'account_signup' %}">サインアップ</a>&ndash;&gt;-->
        <!--&lt;!&ndash;            </li>&ndash;&gt;-->
        <!--            <li class="nav-item">-->
        <!--                <a class="nav-link" href="{% url 'account_login' %}">ログイン</a>-->
        <!--            </li>-->
        <!--            {% endif %}-->
        <!--            {% if user.is_staff %}-->
        <!--            <li class="nav-item">-->
        <!--                <a class="nav-link" href="{% url 'shop:products' %}">商品登録</a>-->
        <!--            </li>-->
        <!--            {% endif %}-->
        <!--            <li class="nav-item">-->
        <!--                <div id="search-wrap" class="fadeUpTrigger">-->
        <!--                    <form role="search" action="{% url 'shop:search' %}" method="GET">-->
        <!--                        <input type="text" name="search" value="{{ request.GET.search }}" id="search-text" placeholder="検索">-->
        <!--&lt;!&ndash;                        <input type="submit" value="検索">&ndash;&gt;-->
        <!--                    </form>-->
        <!--                </div>&lt;!&ndash;/search-wrap&ndash;&gt;-->
        <!--            </li>-->
        <!--        </ul>-->
        <!--    </div>-->
        <!--</nav>-->

        <div class="container">{% block content %} {% endblock %}</div>
    </div> <!-- containers -->
    <footer class="py-2 bg-dark">
        <p class="m-0 text-center text-white">
            &copy; ECsite
        </p>
    </footer>
</div> <!-- wrapper -->
</body>
</html>

templates/shop/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'shop/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'shop/css/slick.css' %}">

  <title>ECサイト</title>
  <script src="{% static 'shop/js/script.js' %}"></script>
  <script src="{% static 'shop/js/jquery-3.6.0.min.js' %}"></script>
  <script src="{% static 'products/js/slick.min.js' %}"></script>
</head>
<body>
<div class="wrapper">
  <div class="containers">

    <header class="header_">
      <div class="header__inner_">
        <div class="header_title_">
          <a class="navbar-brand" href="{% url 'shop:home' %}">ECサイト</a>
        </div>
        <nav>
          <ul class="gnavi">
            <li><a href="{% url 'shop:home' %}">ホーム</a></li>
            <li class="has-child"><a href="{% url 'shop:list' %}">Product</a>
              <ul>
                {% for category in categories %}
                <li><a href="{% url 'shop:category' category.id %}">{{ category.name }}</a></li>
                {% endfor %}
              </ul>
            </li>
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'accounts:my_page' user.id %}">アカウント</a></li>
            {% else %}
            <li><a href="{% url 'account_login' %}">ログイン</a></li>
            {% endif %}
            <li class="current"><a class="nav-link" href="{% url 'shop:cart' %}">カート<span
                    class="badge badge-pill badge-warning">{{ num }}</span></a></li>

            <li><a href="{% url 'shop:contact' %}">CONTACT</a></li>
            <li>
              <form role="search" action="{% url 'shop:search' %}" method="GET">
                <input type="text" name="search" value="{{ request.GET.search }}" id="search-text">
              </form>
            </li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">

      <div class="my-5">
        <h3>ショッピングカート</h3>
      </div>

      <div class="row order">
        <div class="col-md-9 mb-5">
          <div class="card">
            <div class="card-body px-4 py-3">
              {% for cart in carts %}
              <div class="row">
                <div class="col-md-3 text-center">
                  <img src="{{ cart.product.image.url }}" class="img-fluid">
                </div>
                <div class="col-md-6">
                  <h5>{{ cart.product.name}}</h5>
                  <p class="mb-1">
                    数量： {{ cart.amount }}
                  <form action="{% url 'shop:cart_edit' cart.product.id %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="product" value="{{ product.id }}">
                    <input type="hidden" name="product" value="{{ cart.product.id }}">
                    <input type="number" name="amount" min="0">
                    <input class="btn btn-primary" type="submit" value="カートに入れる">
                  </form>
                  <form action="{% url 'shop:delete' cart.product.id %}" method="POST">
                    {% csrf_token %}
                    <input class="btn btn-primary" type="submit" value="削除">
                  </form>
                  </p>
                </div>
                <div class="col-md-3 text-right">
                  <p>
                    価格：
                    <span class="text-danger font-weight-bold">
                {{ cart.product.price }}円
              </span>
                  </p>
                </div>
              </div>
              {% if not forloop.last %}
              <hr/>
              {% endif %} {% empty %}
              <p class="mb-3">カートは空です</p>
              {% endfor %}
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="card">
            <div class="card-body text-center px-2 py-3">
              {% if total %}
              <p>小計：<span class="font-weight-bold">{{ total }}</span>円</p>
              <div class="mb-3">
                <a class="btn btn-warning" href="/">レジに進む</a>
              </div>
              {% endif %}
              <a class="btn btn-primary" href="{% url 'shop:home' %}">買い物を続ける</a>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div> <!-- containers -->
  <footer class="py-2 bg-dark">
    <p class="m-0 text-center text-white">
      &copy; ECsite
    </p>
  </footer>
</div> <!-- wrapper -->
</body>
</html>

<!--<!DOCTYPE html>-->
<!--<html lang="ja">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>カート</title>-->
<!--</head>-->
<!--<body>-->

<!--{% for cart in carts %}-->
<!--<div class="border">-->
<!--    <div>商品名:{{ cart.product.name }}</div>-->
<!--    <div>価格:{{ cart.product.price }}</div>-->


<!--    <div>数量:{{ cart.amount }}</div>-->

<!--&lt;!&ndash;    <div>合計:{{ cart.get_total_price }}円</div>&ndash;&gt;-->
<!--</div>-->


<!--{% endfor %}-->
<!--<hr>-->
<!--小計 ({{ num }} 個の商品) (税込) : \{{ total }}-->

<!--<a href="{% url 'shop:home' %}">戻る</a>-->

<!--</body>-->
<!--</html>-->

templates/shop/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'shop/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'shop/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'shop/css/contact.css' %}">

    <title>ECサイト</title>
    <script src="{% static 'shop/js/script.js' %}"></script>
    <script src="{% static 'shop/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'products/js/slick.min.js' %}"></script>
</head>
<body>
<div class="wrapper">
    <div class="containers">

        <header class="header_">
            <div class="header__inner_">
                <div class="header_title_">
                    <a class="navbar-brand" href="{% url 'shop:home' %}">ECサイト</a>
                </div>
                <nav>
                    <ul class="gnavi">
                        <li><a href="{% url 'shop:home' %}">ホーム</a></li>
                        <li class="has-child"><a href="{% url 'shop:list' %}">Product</a>
                            <ul>
                                {% for category in categories %}
                                <li><a href="{% url 'shop:category' category.id %}">{{ category.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'accounts:my_page' user.id %}">アカウント</a></li>
                        {% else %}
                        <li><a href="{% url 'account_login' %}">ログイン</a></li>
                        {% endif %}
                        <li><a class="nav-link" href="{% url 'shop:cart' %}">カート<span
                                class="badge badge-pill badge-warning">{{ request.num }}</span></a></li>

                        <li class="current"><a href="{% url 'shop:contact' %}">CONTACT</a></li>
                        <li>
                            <form role="search" action="{% url 'shop:search' %}" method="GET">
                                <input type="text" name="search" value="{{ request.GET.search }}" id="search-text">
                            </form>
                        </li>
                    </ul>
                </nav>
            </div>
        </header>

        <div class="container">
            <form method="POST">
                {% csrf_token %}
                <div class="Form">
                    <div class="Form-Item">
                        <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>氏名</p>
                        <input type="text" class="Form-Item-Input" placeholder="例）山田太郎" name="name">
                    </div>
                    <div class="Form-Item">
                        <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>メールアドレス</p>
                        <input type="email" class="Form-Item-Input" placeholder="例）example@example.com" name="email">
                    </div>
                    <div class="Form-Item">
                        <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>件名</p>
                        <input type="email" class="Form-Item-Input" name="title">
                    </div>
                    <div class="Form-Item">
                        <p class="Form-Item-Label isMsg"><span class="Form-Item-Label-Required">必須</span>お問い合わせ内容</p>
                        <textarea class="Form-Item-Textarea" name="contents"></textarea>
                    </div>
                    <input type="submit" class="Form-Btn" value="送信する">
                </div>
            </form>
        </div>
        <div class="container">{% block content %} {% endblock %}</div>
    </div> <!-- containers -->
    <footer class="py-2 bg-dark">
        <p class="m-0 text-center text-white">
            &copy; ECsite
        </p>
    </footer>
</div> <!-- wrapper -->
</body>
</html>

templates/shop/products_create.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>商品登録</title>
    <link rel="stylesheet" href="{% static 'products/css/style.css' %}">
    <script src="{% static 'products/js/script.js' %}"></script>
    <script src="{% static 'products/js/jquery-3.6.0.min.js' %}"></script>
</head>
<body>

<h4>カテゴリー名(親)</h4>
<form method="POST" action="{% url 'shop:category_parent' %}">
    {% csrf_token %}
    <p>カテゴリー名:</p>
    <input type="text" name="name" placeholder="書籍">
    <input type="submit" value="登録">
</form>

<h4>カテゴリー名(子)</h4>
<form method="POST" action="{% url 'shop:category_child' %}">
    {% csrf_token %}
    <p>カテゴリー名:</p>
    <select name="category">
        <option value="">未選択</option>
        {% for category in category %}
        <option value="{{ category.id }}">{{ category.name }}</option>
        {% endfor %}
    </select>
    <input type="text" name="name" placeholder="書籍">
    <input type="submit" value="登録">
</form>

<h4>商品名</h4>
<form method="POST" enctype="multipart/form-data" action="{% url 'shop:products' %}">
    {% csrf_token %}

    <p>カテゴリー:</p>
    <select name="category">
        <option value="">未選択</option>
        {% for category in categories %}
        <option value="{{ category.id }}">{{ category.name }}</option>
        {% endfor %}
    </select>

    <p>サムネイル</p>
    <input type="file" name="image">

    <p>商品名:</p>
    <input type="text" name="name">

    <p>値段:</p>
    <input type="number" name="price">

    <p>運用状況:</p>
    <input type="checkbox" name="situation">

    <p>在庫数</p>
    <input type="number" name="stock">

    <p>説明</p>
    <textarea name="description"></textarea>
    <input type="submit" value="登録">
</form>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<form method="POST" enctype="multipart/form-data" action="{% url 'shop:products_images' %}">
    {% csrf_token %}
    <div id="image_area">
        <p>画像登録:</p>
        <input class="input_image" type="file" name="image">
    </div>
    <p>商品</p>

    <select name="product">
        <option value="">未指定</option>
        {% for product in products %}
        <option value="{{ product.id }}">{{ product.name }}</option>
        {% endfor %}
    </select>

    {# Ajax仕様の送信ボタンに仕立てる。ID名を指定して、type="button"にする。 #}

    {# <input type="submit" value="登録"> #}

    <input id="image_submit" type="button" value="登録(Ajax)">
</form>

<a href="{% url 'shop:home' %}">戻る</a>
</body>
</html>